### PR TITLE
Update JDA to version 5 alpha 9

### PR DESCRIPTION
**Pull request by GigaFyde**
This will ensure it'll actually compile in jitpack

Currently the build fails, as jitpack can't find the required artifacts

### CODE REVIEW

**Comment by Walkyst** [comment]
Isn't it compiled https://jitpack.io/com/github/walkyst/lavalink-client/f8d5977e44/build.log?

**Comment by GigaFyde** [comment]
Well then, apparently jitpack changed their mind or something.
As that build had been failing for days for me

**Comment by Walkyst** [comment]
Probably you are looked at https://jitpack.io/com/github/Walkyst/Lavalink-Client/f8d5977e44/build.log which is failed previusly, just rebuilded it and now it's fine

**Comment by GigaFyde** [comment]
Yea, clearly something changed since, as it seems to build just fine now

**Pull request closed without merging**
